name: Publish NuGet Package

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: windows-latest

    environment: Nuget

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore SamSharp.sln

      - name: Build
        shell: pwsh
        run: |
          dotnet build SamSharp.sln `
            --configuration Release `
            --no-restore `
            /p:Version=$env:VERSION

      - name: Test
        shell: pwsh
        run: |
          dotnet test SamSharp.sln `
            --configuration Release `
            --no-build

      - name: Pack NuGet Package
        shell: pwsh
        run: |
          dotnet pack .\SamSharp\SamSharp.csproj `
            --configuration Release `
            --no-build `
            --output ./nupkgs `
            /p:PackageVersion=$env:VERSION

      - name: Verify Package
        shell: pwsh
        run: |
          Get-ChildItem ./nupkgs/*.nupkg

      - name: NuGet Login (Trusted Publishing)
        id: login
        uses: NuGet/login@v1
        with:
          user: MegaChuck64

      - name: Publish to NuGet
        shell: pwsh
        run: |
          Get-ChildItem ./nupkgs/*.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName `
              --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
              --source "https://api.nuget.org/v3/index.json"
          }
