name: Publish NuGet Package

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: windows-latest

    environment: Nuget

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore SamSharp.csproj

      - name: Build
        shell: pwsh
        run: |
          dotnet build SamSharp.csproj `
            --configuration Release `
            --no-restore `
            /p:Version=$env:VERSION

      - name: Test
        run: dotnet test SamSharpTest.csproj --configuration Release --no-build

      - name: Pack
        shell: pwsh
        run: |
          dotnet pack SamSharp.csproj `
            --configuration Release `
            --no-build `
            --output ./nupkgs `
            /p:PackageVersion=$env:VERSION

      - name: List Generated Packages
        shell: pwsh
        run: |
          Write-Host "Current Directory:"
          Get-Location

          Write-Host "`nGenerated packages:"
          Get-ChildItem -Recurse -Filter *.nupkg

      - name: NuGet Login (Trusted Publishing)
        id: login
        uses: NuGet/login@v1
        with:
          user: MegaChuck64

      - name: Publish to NuGet
        shell: pwsh
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" `
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
            --source "https://api.nuget.org/v3/index.json"
